name: mswm_test
description: "Stakful Casino"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  firebase_analytics: ^10.6.3
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  flutter_inappwebview: ^5.7.2+3
  http: ^1.1.0
  provider: ^6.1.1
  firebase_messaging: ^14.2.2
  firebase_remote_config:
  firebase_core: ^2.1.1
  intl: ^0.19.0
  ###
  get: ^4.6.6
  smooth_page_indicator: ^1.2.0+3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/spinner/
    - assets/components/
    - assets/slots/
    - assets/slots2/
    - assets/slots3/
  fonts:
    - family: Acme
      fonts:
        - asset: assets/fonts/Acme-Regular.ttf